name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.3.0

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v20

      - name: Setup Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@v13

      - name: Build WASM with Nix
        run: |
          # Use Makefile for consistent build process
          make build

      - name: Verify build artifacts
        run: |
          echo "## Build Artifacts" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Generated files:" >> $GITHUB_STEP_SUMMARY
          ls -lh docs/ | tee -a $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          if [ -f docs/app.wasm ] && [ -f docs/ghc_wasm_jsffi.js ] && [ -f docs/index.html ] && [ -f docs/index.js ]; then
            echo "✅ All required files generated successfully!" >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ Missing required files!" >> $GITHUB_STEP_SUMMARY
            exit 1
          fi

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: ./docs

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5